### ISSUE TITLE
Strange $17 at the end of the prompt

### ISSUE THREAD

**Issue by n-peugnet** [lyze/posh-git-sh#38]
Thank you very much for porting this extension to bash.
I just tried to install it yesterday and everything is working fine, except that I have a strange `$17` at the end of my prompt when it's using git-prompt

```
nicolas@X260-NICOLAS:~ 
$ cd Source/java/slipdb/
nicolas@X260-NICOLAS:~/Source/java/slipdb [feat/filter-object ≡]$17
$ rm src/ -r
nicolas@X260-NICOLAS:~/Source/java/slipdb [feat/filter-object ≡ +0 ~0 -106]$17
$ git reset --hard 
HEAD is now at 39b76c6 implement our filter object idea
nicolas@X260-NICOLAS:~/Source/java/slipdb [feat/filter-object ≡]$17
$ 
```

Command prompt configuration:
```bash
PROMPT_COMMAND='__posh_git_ps1 "\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] " "\n\$ ";'$PROMPT_COMMAND
```

**Comment by n-peugnet** [comment]
Sorry I just understood, reading the pull request #36, that this refers to the number of stashes. It was not written on the README and I didn't remember seeing this behavior in the original posh-git, that's why I didn't understood in the first place.

**Comment by lyze** [comment]
[This feature is disabled by default](https://github.com/dahlbyk/posh-git/blob/be4563890df984a62fa5e8598e4d6c310e1d9b5f/src/PoshGitTypes.ps1#L255) in posh-git, so we're diverging a bit here.

[Implementation](https://github.com/dahlbyk/posh-git/blob/d4fd8e6704fa1599ad1c31316a8dab71f0f60c9b/src/GitPrompt.ps1#L833)
[Call site](https://github.com/dahlbyk/posh-git/blob/d4fd8e6704fa1599ad1c31316a8dab71f0f60c9b/src/GitPrompt.ps1#L218)

**Comment by lyze** [comment]
I'll look to update the documentation.

**Comment by rdnlsmith** [comment]
@lyze Would it be preferable to have the same default? It seems as though they did this [for performance reasons](https://github.com/dahlbyk/posh-git/issues/459).

Also, posh-git has a different display format, which seems cleaner to me personally:

![image](https://user-images.githubusercontent.com/4039042/55042507-2a3b4a80-5008-11e9-891f-b4c19a2a8910.png)

vs.

![image](https://user-images.githubusercontent.com/4039042/55042685-07f5fc80-5009-11e9-88f9-a14d35e7d66b.png)

(which is also hard to see using default Ubuntu terminal colors)

On the other hand, posh-git controls this with one setting (`EnableStashStatus`) rather than two&mdash;if the stash status is shown at all, it includes the count. I'm not sure what the display ought to look like if posh-git-sh were to adopt the `( )` format but still keep `bash.showStashState` and `bash.showStashCount` as separate options.

**Comment by lyze** [comment]
I'll find some time soon to make the option values and names match (and the rest of the options as well) the corresponding ones in posh-git.

**Comment by rdnlsmith** [comment]
I’d be glad to help out if you want!

**Comment by lyze** [comment]
There are still some differences with posh-git, but I'll look to close them out more by trying to add some simple acceptance tests.
